config/routes.rb
Rails.application.routes.draw do
  resources :sign_ups

  root 'sign_ups#new'

end

app/models/sign_up.rb
class SignUp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sign_ups_controller.rb
class SignUpsController < ApplicationController
  before_action :set_sign_up, only: [:show, :edit, :update, :destroy]

  # GET /sign_ups
  # GET /sign_ups.json
  def index
    @sign_ups = SignUp.all
    @sign_up = SignUp.new
  end

  # GET /sign_ups/1
  # GET /sign_ups/1.json
  def show
  end

  # GET /sign_ups/new
  def new
    @sign_up = SignUp.new
  end

  # GET /sign_ups/1/edit
  def edit
  end

  # POST /sign_ups
  # POST /sign_ups.json
  def create
    @sign_up = SignUp.new(sign_up_params)

    email = @sign_up.email

    begin
      response = Clearbit::Enrichment.find(email: email, stream: true)

      if response && response.person != nil
        @name = response.person.name.fullName
        @company_name = response.person.employment.name

        if response.company
          @company_name = response.company.name
          @phone_number = response.company.phone || response.company.site.phoneNumbers[0]
          @company_size = response.company.metrics.employees || response.company.metrics.employeesRange
        end
      end

      respond_to do |format|
        format.html { render :new }
        format.js
      end
    rescue Nestful::ResourceInvalid
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    rescue Nestful::ClientError
      @error = true
      respond_to do |format|
        format.js
      end
    end
    
  end

  # PATCH/PUT /sign_ups/1
  # PATCH/PUT /sign_ups/1.json
  def update
    respond_to do |format|
      if @sign_up.update(sign_up_params)
        format.html { redirect_to @sign_up, notice: 'Sign up was successfully updated.' }
        format.json { render :show, status: :ok, location: @sign_up }
      else
        format.html { render :edit }
        format.json { render json: @sign_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sign_ups/1
  # DELETE /sign_ups/1.json
  def destroy
    @sign_up.destroy
    respond_to do |format|
      format.html { redirect_to sign_ups_url, notice: 'Sign up was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sign_up
      @sign_up = SignUp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sign_up_params
      params.require(:sign_up).permit(:email, :name, :company_name, :company_size, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sign_ups_helper.rb
module SignUpsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frictionless Sign-Up</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Nunito:600,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sign_ups/_form.html.erb
<%= form_for [@sign_up], remote:true do |f| %>
  <% if @sign_up.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sign_up.errors.count, "error") %> prohibited this sign_up from being saved:</h2>

      <ul>
      <% @sign_up.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <p class="warning" id="email-warning">*Please enter a valid email address.</p><br>
    <%= f.email_field :email, autocomplete: 'email', required: true %>
  </div>

  <div id="hidden-form">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label 'Company Name' %><br>
      <%= f.text_field :company_name %>
    </div>
      <div class="field">
      <%= f.label :company_size %><br>
      <%= f.text_field :company_size %>
    </div>
      <div class="field">
      <%= f.label :phone_number %><br>
      <%= f.text_field :phone_number %>
    </div>
  </div>

  <p>Please fill in all fields.</p>

<% end %>

app/views/sign_ups/create.js.erb
populateForm();
enableFields();
expandContainer();

function populateForm(){
  $('#sign_up_name').val('<%= @name %>')
  $('#sign_up_company_name').val(decodeEntities('<%= @company_name %>'))
  $('#sign_up_company_size').val('<%= @company_size %>')
  $('#sign_up_phone_number').val('<%= @phone_number %>')
}

function expandContainer(){
  if ($('#form-container').hasClass('expanded')){
    highlightMissingFields()
  } else {
    $('#form-container').addClass('expanded');
    window.setTimeout(function(){
      highlightMissingFields();
    },500)
  }
}

function highlightMissingFields(){
  var children = $('#hidden-form').find('input');
  var index;

  for ( var i = 0; i < children.length; i++ ){
    if (!$(children[i]).val()){
      if ( !index && index !== 0 ){
        index = i
      }
    }
  }

  $(children[index]).focus();
}

function enableFields(){
  var children = $('#hidden-form').find('input');

  for ( var i = 0; i < children.length; i++ ){
    $(children[i]).attr('disabled',false);
  }
}

// Safe way to decode HTML entities
// http://stackoverflow.com/questions/1147359/how-to-decode-html-entities-using-jquery/1395954#1395954
function decodeEntities(encodedString) {
  var textArea = document.createElement('textarea');
  textArea.innerHTML = encodedString;
  return textArea.value;
}

if('<%= @error %>'){
  $('#form-container').before("<p style='background-color:red'>API Quota exceeded.</p>")
}

app/views/sign_ups/edit.html.erb
<h1>Editing Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Show', @sign_up %> |
<%= link_to 'Back', sign_ups_path %>

app/views/sign_ups/index.html.erb
<br>
<h1><%=  %></h1>
<br>
<br>
<p id="notice"><%= notice %></p>

<h1>Listing Sign Ups</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Companyname</th>
      <th>Companysize</th>
      <th>Phonenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sign_ups.each do |sign_up| %>
      <tr>
        <td><%= sign_up.email %></td>
        <td><%= sign_up.firstname %></td>
        <td><%= sign_up.lastname %></td>
        <td><%= sign_up.companyname %></td>
        <td><%= sign_up.companysize %></td>
        <td><%= sign_up.phonenumber %></td>
        <td><%= link_to 'Show', sign_up %></td>
        <td><%= link_to 'Edit', edit_sign_up_path(sign_up) %></td>
        <td><%= link_to 'Destroy', sign_up, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sign up', new_sign_up_path %>

app/views/sign_ups/new.html.erb
<div id="form-container">

<h1>SAMPLE SIGNUP FORM</h1>

<%= render 'form' %>

</div>

app/views/sign_ups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @sign_up.email %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @sign_up.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @sign_up.lastname %>
</p>

<p>
  <strong>Companyname:</strong>
  <%= @sign_up.companyname %>
</p>

<p>
  <strong>Companysize:</strong>
  <%= @sign_up.companysize %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @sign_up.phonenumber %>
</p>

<%= link_to 'Edit', edit_sign_up_path(@sign_up) %> |
<%= link_to 'Back', sign_ups_path %>